services:
  # Frontend React Application (Development - simplified)
  techbirds-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: techbirds-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5001
    networks:
      - techbirds-network
    restart: unless-stopped

  # Database (PostgreSQL)
  techbirds-db:
    image: postgres:15-alpine
    container_name: techbirds-db-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=techbirds
      - POSTGRES_USER=techbirds_user
      - POSTGRES_PASSWORD=techbirds_password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - techbirds-network
    restart: unless-stopped

  # Redis for caching
  techbirds-redis:
    image: redis:7-alpine
    container_name: techbirds-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - techbirds-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  techbirds-network:
    driver: bridge